// src/components/PersonDetail.vue
<script>
import FilmGrid from './FilmGrid.vue';
import StudioLink from './StudioLink.vue';

function addToMeta(films, title, meta) {
  films.forEach((film) => {
    if (meta[film.id]) {
      meta[film.id] += ` / ${title}`;
    } else {
      meta[film.id] = title;
    }
  });
}

export default {
  props: {
    person: Object,
  },
  computed: {
    age() {
      return this.person
        ? this.calculateAge(
            {
              year: this.person.birthYear,
              month: this.person.birthMonth,
              day: this.person.birthDay,
            },
            {
              year: this.person.deathYear || new Date().getFullYear(),
              month: this.person.deathMonth || undefined,
              day: this.person.deathDay || undefined,
            }
          )
        : '?';
    },
    born() {
      return this.person
        ? this.formatDate({
            year: this.person.birthYear,
            month: this.person.birthMonth,
            day: this.person.birthDay,
          })
        : '?';
    },
    died() {
      return this.person
        ? this.formatDate({
            year: this.person.deathYear,
            month: this.person.deathMonth,
            day: this.person.deathDay,
          })
        : '?';
    },
    formattedName() {
      return this.person.alias
        ? this.person.alias
        : `${this.person.firstName} ${this.person.lastName}`;
    },
    hasStudio() {
      return this.person && this.person.founded && this.person.founded.length;
    },
    hasAnimationCredit() {
      return this.person && this.person.animated && this.person.animated.length;
    },
    hasDirectingCredit() {
      return this.person && this.person.directed && this.person.directed.length;
    },
    hasWritingCredit() {
      return this.person && this.person.wrote && this.person.wrote.length;
    },
    hasComposingCredit() {
      return this.person && this.person.composed && this.person.composed.length;
    },
  },
  methods: {
    calculateAge(date1, date2) {
      const yearDiff = Math.floor(date2.year - date1.year);

      if (date2.month && date1.month) {
        if (date1.day && date2.day) {
          if (date2.month >= date1.month && date2.day >= date1.day) return yearDiff;
          return yearDiff - 1;
        }
        if (date2.month >= date1.month) return yearDiff;
        return yearDiff - 1;
      }

      return yearDiff;
    },
    formatDate({ year, month, day }) {
      if (!month || !day) return year;
      return `${year}-${month}-${day}`;
    },
  },
  components: { FilmGrid, StudioLink },
};
</script>

<template>
  <div v-if="person" class="ani-persondetail">
    <div class="ani-persondetail-img">
      <img :src="person.image.url" :alt="person.image.title" width="400" />
    </div>
    <div class="ani-persondetail-details">
      <h1 class="ani-persondetail-title">
        {{ formattedName }} {{ !person.alias && person.kanji ? `(${person.kanji})` : '' }}
      </h1>
      <p>{{ person.description }}</p>
      <div class="ani-persondetail-meta">
        <div class="ani-meta">
          <div v-if="person.alias" class="ani-meta-key">Given Name</div>
          <div v-if="person.alias" class="ani-meta-val">
            {{ person.firstName }} {{ person.lastName }}
            {{ person.kanji ? ` (${person.kanji})` : '' }}
          </div>

          <div v-if="person.birthYear" class="ani-meta-key">Born</div>
          <div v-if="person.birthYear" class="ani-meta-val">{{ born }}</div>

          <div v-if="person.birthYear" class="ani-meta-key">Age</div>
          <div v-if="person.birthYear" class="ani-meta-val">{{ age }}</div>

          <div v-if="person.deathYear" class="ani-meta-key">Died</div>
          <div v-if="person.deathYear" class="ani-meta-val">{{ died }}</div>

          <div class="ani-meta-key">Country</div>
          <div class="ani-meta-val">{{ person.country }}</div>

          <div v-if="hasStudio" class="ani-meta-key">Founded</div>
          <div v-if="hasStudio">
            <StudioLink v-for="studio in person.founded" :key="studio.id" :studio="studio" />
          </div>

          <div v-if="hasAnimationCredit" class="ani-meta-key">Animated</div>
          <div v-if="hasAnimationCredit"><FilmGrid :films="person.animated" small /></div>

          <div v-if="hasDirectingCredit" class="ani-meta-key">Directed</div>
          <div v-if="hasDirectingCredit"><FilmGrid :films="person.directed" small /></div>

          <div v-if="hasWritingCredit" class="ani-meta-key">Wrote</div>
          <div v-if="hasWritingCredit"><FilmGrid :films="person.wrote" small /></div>

          <div v-if="hasComposingCredit" class="ani-meta-key">Composed</div>
          <div v-if="hasComposingCredit"><FilmGrid :films="person.composed" small /></div>
        </div>
      </div>
    </div>
  </div>
  <div v-else class="ani-persondetail">
    <div class="ani-skeleton--img" />
    <div class="ani-persondetail-details">
      <h1 class="ani-persondetail-title">
        <div class="ani-skeleton">Winsor McCay</div>
      </h1>
    </div>
  </div>
</template>

// src/components/PersonDetail/index.tsx
import * as preact from '/web_modules/preact.js';

import FilmGrid from '../FilmGrid/index.js';
import { MetaTable, MetaKey, MetaValue } from '../MetaTable/index.js';
import SkeletonText from '../SkeletonText/index.js';
import SkeletonImg from '../SkeletonImg/index.js';
import { OnePersonQuery } from '../../types/graphql';
import { age, formatDate } from '../../utils/date.js';
import StudioLink from '../StudioLink/index.js';

interface PersonDetailProps {
  person?: OnePersonQuery['person'];
}

const formatName = (person: OnePersonQuery['person']) =>
  person.alias ? person.alias : `${person.firstName} ${person.lastName}`;

/* eslint-disable no-param-reassign */
function addToMeta(
  films: OnePersonQuery['person']['directed'],
  title: string,
  meta: { [key: string]: string }
) {
  films.forEach(film => {
    if (meta[film.id]) {
      meta[film.id] += ` / ${title}`;
    } else {
      meta[film.id] = title;
    }
  });
}
/* eslint-enable no-param-reassign */

const PersonDetail: preact.FunctionComponent<PersonDetailProps> = ({ person }) => {
  if (person) {
    const name = formatName(person);
    const filmMeta: { [key: string]: string } = {};
    addToMeta(person.directed, 'Director', filmMeta);
    addToMeta(person.wrote, 'Writer', filmMeta);
    addToMeta(person.composed, 'Composer', filmMeta);
    let films = [...person.directed, ...person.wrote, ...person.composed];
    films = films.filter(({ id }, i) => films.findIndex(film => film.id === id) === i);
    films.sort((a, b) => a.releaseYear - b.releaseYear);

    return (
      <div className="personDetail">
        <div className="personDetail-img">
          <img src={person.image.url} alt={person.image.title} width="400" />
        </div>
        <div className="personDetail-details">
          <h1 className="personDetail-title">
            {name} {!person.alias && person.kanji && `(${person.kanji})`}
          </h1>
          <p>{person.description}</p>
          <div className="personDetail-meta">
            <MetaTable>
              {person.alias && [
                <MetaKey>Given Name</MetaKey>,
                <MetaValue>
                  {person.firstName} {person.lastName}
                  {person.kanji && ` (${person.kanji})`}
                </MetaValue>,
              ]}
              {person.birthYear && [
                <MetaKey>Born</MetaKey>,
                <MetaValue>
                  {formatDate({
                    year: person.birthYear,
                    month: person.birthMonth,
                    day: person.birthDay,
                  })}
                </MetaValue>,
                <MetaKey>Age</MetaKey>,
                <MetaValue>
                  {age(
                    { year: person.birthYear, month: person.birthMonth, day: person.birthDay },
                    {
                      year: person.deathYear || new Date().getFullYear(),
                      month: person.deathMonth || undefined,
                      day: person.deathDay || undefined,
                    }
                  )}
                </MetaValue>,
              ]}
              {person.deathYear && [
                <MetaKey>Died</MetaKey>,
                <MetaValue>
                  {formatDate({
                    year: person.deathYear,
                    month: person.deathMonth,
                    day: person.deathDay,
                  })}
                </MetaValue>,
              ]}
              <MetaKey>Country</MetaKey>
              <MetaValue>{person.country}</MetaValue>
              {Array.isArray(person.founded) &&
                person.founded.length > 0 && [
                  <MetaKey>Founded</MetaKey>,
                  <MetaValue>
                    {person.founded.map(studio => (
                      <StudioLink key={studio.id} studio={studio} />
                    ))}
                  </MetaValue>,
                ]}
            </MetaTable>
          </div>
        </div>
        <div className="personDetail-films">
          <h2 className="personDetail-subtitle">Films</h2>
          <FilmGrid films={films} meta={filmMeta} />
        </div>
      </div>
    );
  }
  return (
    <div className="personDetail">
      <SkeletonImg />
      <div className="personDetail-details">
        <h1 className="personDetail-title">
          <SkeletonText>Winsor McCay</SkeletonText>
        </h1>
      </div>
    </div>
  );
};

export default PersonDetail;
