// src/components/AnimationGrid.vue
<script>
export default {
  props: {
    sequences: Array,
  },
};
</script>

<template>
  <div class="ani-animationgrid">
    <a
      v-for="seq in sequences"
      :key="seq.url"
      :href="seq.url"
      class="ani-animationgrid-item"
      rel="noopener noreferrer"
      target="_blank"
      :data-id="seq.id"
    >
      <img :src="seq.image.url" :alt="seq.image.title" width="300" height="162" />
    </a>
  </div>
</template>

// src/components/AnimationGrid/index.tsx
import * as preact from '/web_modules/preact.js';
import { OneFilmQuery } from '../../types/graphql';

interface AnimationGridProps {
  animationSequences: OneFilmQuery['film']['animationSequences'];
}

const AnimationGrid: preact.FunctionComponent<AnimationGridProps> = ({ animationSequences }) => (
  <div className="animationGrid">
    {animationSequences.map(({ id, url, image }) => (
      <a
        key={url}
        className="animationGrid-item"
        href={url}
        rel="noopener noreferrer"
        target="_blank"
        data-id={id}
      >
        <img src={image.url} alt={image.title} />
      </a>
    ))}
  </div>
);

export default AnimationGrid;
