// src/components/StudioDetail.vue
<script>
import FilmGrid from './FilmGrid.vue';
import PersonLink from './PersonLink.vue';

export default {
  props: {
    studio: Object,
  },
  computed: {
    hasFounders() {
      return this.studio && this.studio.founders && this.studio.founders.length;
    },
  },
  components: { FilmGrid, PersonLink },
};
</script>

<template>
  <div v-if="studio" class="ani-studiodetail">
    <div class="ani-studiodetail-img">
      <img :src="studio.image.url" :alt="studio.name" width="400" />
    </div>
    <div class="ani-studiodetail-details">
      <h1 class="ani-studiodetail-title">{{ studio.name }}</h1>
      <div class="ani-studiodetail-meta">
        <div class="ani-meta">
          <div v-if="studio.foundedYear" class="ani-meta-key">Founded</div>
          <div v-if="studio.foundedYear" class="ani-meta-val">{{ studio.foundedYear }}</div>

          <div v-if="hasFounders" class="ani-meta-key">Founders</div>
          <div v-if="hasFounders" class="ani-meta-val">
            <PersonLink v-for="person in studio.founders" :key="person.id" :person="person" />
          </div>

          <div v-if="studio.country" class="ani-meta-key">Country</div>
          <div v-if="studio.country" class="ani-meta-val">{{ studio.country }}</div>

          <div v-if="studio.city" class="ani-meta-key">City</div>
          <div v-if="studio.city">{{ studio.city }}</div>
        </div>
      </div>
    </div>
    <div class="ani-studiodetail-films">
      <h2 class="ani-studiodetail-subtitle">Films</h2>
      <FilmGrid :films="studio.films" />
    </div>
  </div>
  <div v-else class="ani-studiodetail">
    <SkeletonImg />
    <div class="ani-studiodetail-details">
      <h1 class="ani-studiodetail-title">
        <div class="ani-skeleton">Studio Ghibli</div>
      </h1>
    </div>
    <div class="ani-studiodetail-films">
      <h2 class="ani-studiodetail-subtitle">
        <div class="ani-skeleton">Films</div>
      </h2>
      <FilmGrid />
    </div>
  </div>
</template>

// src/components/StudioDetail/index.tsx
import * as preact from '/web_modules/preact.js';

import FilmGrid from '../FilmGrid/index.js';
import { MetaTable, MetaKey, MetaValue } from '../MetaTable/index.js';
import PersonLink from '../PersonLink/index.js';
import SkeletonText from '../SkeletonText/index.js';
import SkeletonImg from '../SkeletonImg/index.js';
import { OneStudioQuery } from '../../types/graphql';

interface StudioDetailProps {
  studio?: OneStudioQuery['studio'];
}

const StudioDetail: preact.FunctionComponent<StudioDetailProps> = ({ studio }) => {
  if (studio) {
    return (
      <div className="studioDetail">
        <div className="studioDetail-img">
          <img src={studio.image.url} alt={studio.name} width="400" />
        </div>
        <div className="studioDetail-details">
          <h1 className="studioDetail-title">{studio.name}</h1>
          <div className="studioDetail-meta">
            <MetaTable>
              {studio.foundedYear && [
                <MetaKey>Founded</MetaKey>,
                <MetaValue>{studio.foundedYear}</MetaValue>,
              ]}
              {Array.isArray(studio.founders) &&
                studio.founders.length > 0 && [
                  <MetaKey>Founders</MetaKey>,
                  <MetaValue>
                    {studio.founders.map(founder => (
                      <PersonLink key={founder.id} person={founder} />
                    ))}
                  </MetaValue>,
                ]}
              {studio.country && [
                <MetaKey>Country</MetaKey>,
                <MetaValue>{studio.country}</MetaValue>,
              ]}
              {studio.city && [<MetaKey>City</MetaKey>, <MetaValue>{studio.city}</MetaValue>]}
            </MetaTable>
          </div>
        </div>
        <div className="studioDetail-films">
          <h2 className="studioDetail-subtitle">Films</h2>
          <FilmGrid films={studio.films} />
        </div>
      </div>
    );
  }
  return (
    <div className="studioDetail">
      <SkeletonImg />
      <div className="studioDetail-details">
        <h1 className="studioDetail-title">
          <SkeletonText>Studio Ghibli</SkeletonText>
        </h1>
      </div>
      <div className="studioDetail-films">
        <h2 className="studioDetail-subtitle">
          <SkeletonText>Films</SkeletonText>
        </h2>
        <FilmGrid />
      </div>
    </div>
  );
};

export default StudioDetail;
