// src/routes/Studio.svelte
<script>
  import Block from '../components/Block.svelte';
  import StudioDetail from '../components/StudioDetail.svelte';
  import NavBack from '../components/NavBack.svelte';
  import Wrapper from '../components/Wrapper.svelte';
  import { GRAPHQL_URL } from '../lib/constants.js';
  import fetchGQL from '../lib/gql.js';
  import query from '../graphql/one-studio.graphql.js';

  // props
  export let id;

  // state
  const resp = fetchGQL({ url: GRAPHQL_URL, query, variables: { id } });
</script>

<Block>
  <Wrapper>
    <NavBack />
    <StudioDetail studio={resp && resp.data ? resp.data.studio : undefined} />
  </Wrapper>
</Block>

// src/pages/studio.tsx
import * as preact from '/web_modules/preact.js';

import Block from '../components/Block/index.js';
import StudioDetail from '../components/StudioDetail/index.js';
import NavBack from '../components/NavBack/index.js';
import Wrapper from '../components/Wrapper/index.js';
import { GRAPHQL_URL } from '../lib/constants.js';
import { OneStudioQuery, OneStudioQueryVariables } from '../types/graphql';
import useGql from '../hooks/use-gql.js';
import query from '../graphql/one-studio.graphql.js';

interface StudioPageProps {
  id?: string;
}

const StudioPage: preact.FunctionComponent<StudioPageProps> = ({ id }) => {
  const { data } = useGql<OneStudioQuery, OneStudioQueryVariables>({
    url: GRAPHQL_URL,
    query,
    variables: { id },
  });

  return (
    <Block>
      <Wrapper>
        <NavBack />
        <StudioDetail studio={data ? data.studio : undefined} />
      </Wrapper>
    </Block>
  );
};

export default StudioPage;
