// src/components/FilmDetail.vue
<script>
import AnimationGrid from './AnimationGrid.vue';
import PersonLink from './PersonLink.vue';
import StudioLink from './StudioLink.vue';

export default {
  props: { film: Object },
  computed: {
    hasStudio() {
      return this.film && this.film.studio;
    },
    hasDirectors() {
      return this.film && Array.isArray(this.film.directors) && this.film.directors.length;
    },
    hasWriters() {
      return this.film && Array.isArray(this.film.writers) && this.film.writers.length;
    },
    hasComposers() {
      return this.film && Array.isArray(this.film.composers) && this.film.composers.length;
    },
    hasSakuga() {
      return (
        this.film &&
        Array.isArray(this.film.animationSequences) &&
        this.film.animationSequences.length
      );
    },
    hasReleases() {
      return this.film && Array.isArray(this.film.releases) && this.film.releases.length;
    },
  },
  components: { AnimationGrid, PersonLink, StudioLink },
};
</script>

<template>
  <div v-if="film" class="ani-filmdetail">
    <img class="ani-filmdetail-img" :src="film.image.url" :alt="film.title" width="400" />
    <div class="ani-filmdetail-details">
      <h1 class="ani-filmdetail-title">
        {{ film.title }}
        <br />
        {{ film.titleEN }}
      </h1>
      {{ film.releaseYear }}
      <div class="ani-filmdetail-meta">
        <div class="ani-meta">
          <div v-if="hasStudio" class="ani-meta-key">Studio</div>
          <div v-if="hasStudio" class="ani-meta-val">
            <StudioLink :studio="film.studio" />
          </div>

          <div v-if="hasDirectors" class="ani-meta-key">
            Director{{ film.directors.length > 1 ? 's' : '' }}
          </div>
          <div v-if="hasDirectors" class="ani-meta-val">
            <PersonLink v-for="person in film.directors" :key="person.id" :person="person" />
          </div>

          <div v-if="hasWriters" class="ani-meta-key">
            Writer{{ film.writers.length > 1 ? 's' : '' }}
          </div>
          <div v-if="hasWriters" class="ani-meta-val">
            <PersonLink v-for="person in film.writers" :key="person.id" :person="person" />
          </div>

          <div v-if="hasComposers" class="ani-meta-key">
            Composer{{ film.composers.length > 1 ? 's' : '' }}
          </div>
          <div v-if="hasComposers" class="ani-meta-val">
            <PersonLink v-for="person in film.composers" :key="person.id" :person="person" />
          </div>
        </div>
      </div>
      <div v-if="hasSakuga" class="ani-filmdetail-animations">
        <h2 class="ani-filmdetail-subtitle">Sakuga</h2>
        <AnimationGrid :sequences="film.animationSequences" />
      </div>
      <div v-if="hasReleases">
        <h2 class="ani-filmdetail-subtitle">Releases</h2>
        <div v-for="(rel, i) in film.releases" :key="i">
          <div>
            <div>{{ rel.country }}</div>
            <div>{{ rel.releaseYear }}-{{ rel.releaseMonth }}-{{ rel.releaseDay }}</div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div v-else class="ani-filmdetail">
    <div class="ani-skeleton--img"></div>
    <div class="ani-filmdetail-details">
      <h1 class="ani-filmdetail-title">
        <div class="ani-skeleton">This movie is loading</div>
      </h1>
      <div class="ani-skeleton">2020</div>
    </div>
  </div>
</template>

// src/components/FilmDetail/index.tsx
import * as preact from '/web_modules/preact.js';

import AnimationGrid from '../AnimationGrid/index.js';
import { MetaTable, MetaKey, MetaValue } from '../MetaTable/index.js';
import PersonLink from '../PersonLink/index.js';
import SkeletonImg from '../SkeletonImg/index.js';
import SkeletonText from '../SkeletonText/index.js';
import StudioLink from '../StudioLink/index.js';
import { OneFilmQuery } from '../../types/graphql';

interface FilmDetailProps {
  film?: OneFilmQuery['film'];
}

const FilmDetail: preact.FunctionComponent<FilmDetailProps> = ({ film }) => {
  if (film) {
    return (
      <div className="filmDetail">
        <img className="filmDetail-img" src={film.image.url} alt={film.title} width="400" />
        <div className="filmDetail-details">
          <h1 className="filmDetail-title">
            {film.title}
            <br />
            {film.titleEN}
          </h1>
          {film.releaseYear}
          <div className="filmDetail-meta">
            <MetaTable>
              {film.studio && [
                <MetaKey>Studio</MetaKey>,
                <MetaValue>
                  <StudioLink studio={film.studio} />
                </MetaValue>,
              ]}
              {Array.isArray(film.directors) &&
                film.directors.length > 0 && [
                  <MetaKey>Director{film.directors.length > 1 && 's'}</MetaKey>,
                  <MetaValue>
                    {film.directors.map(person => (
                      <PersonLink key={person.id} person={person} />
                    ))}
                  </MetaValue>,
                ]}
              {Array.isArray(film.writers) &&
                film.writers.length > 0 && [
                  <MetaKey>Writer{film.writers.length > 1 && 's'}</MetaKey>,
                  <MetaValue>
                    {film.writers.map(person => (
                      <PersonLink key={person.id} person={person} />
                    ))}
                  </MetaValue>,
                ]}
              {Array.isArray(film.composers) &&
                film.composers.length > 0 && [
                  <MetaKey>Composer{film.composers.length > 1 && 's'}</MetaKey>,
                  <MetaValue>
                    {film.composers.map(person => (
                      <PersonLink key={person.id} person={person} />
                    ))}
                  </MetaValue>,
                ]}
            </MetaTable>
          </div>
          <div className="filmDetail-animations">
            {Array.isArray(film.animationSequences) &&
              film.animationSequences.length > 0 && [
                <h2 className="filmDetail-subtitle">Animation Sequences</h2>,
                <AnimationGrid animationSequences={film.animationSequences} />,
              ]}
          </div>
          {Array.isArray(film.releases) && film.releases.length > 0 && (
            <div>
              <h2 className="filmDetail-subtitle">Releases</h2>
              <div>
                {film.releases.map(release => (
                  <div>
                    <div>{release.country}</div>
                    <div>
                      {release.releaseYear}-{release.releaseMonth}-{release.releaseDay}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }
  return (
    <div className="filmDetail">
      <SkeletonImg />
      <div className="filmDetail-details">
        <h1 className="filmDetail-title">
          <SkeletonText>This movie is loading</SkeletonText>
        </h1>
        <SkeletonText>2020</SkeletonText>
      </div>
    </div>
  );
};

export default FilmDetail;
