// src/components/AnimationGrid.vue
<script>
export default {
  props: {
    sequences: Array,
  },
};
</script>

<template>
  <div class="ani-animationgrid">
    <a
      v-for="seq in sequences"
      :key="seq.url"
      :href="seq.url"
      class="ani-animationgrid-item"
      rel="noopener noreferrer"
      target="_blank"
      :data-id="seq.id"
    >
      <img :src="seq.image.url" :alt="seq.image.title" width="300" height="162" />
    </a>
  </div>
</template>

// src/components/AnimationGrid.svelte
<script>
  let animationSequences = [];
</script>

<style>
  .animationGrid {
    display: grid;
    grid-gap: 1.5rem;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  }

  .animationGrid-item {
    border-radius: 0.25rem;
    display: block;
    overflow: hidden;
    position: relative;
  }

  .animationGrid::after {
    background: hsl(var(--black));
    border-radius: 0.25em;
    color: hsl(var(--white));
    content: attr(data-id);
    font-size: var(--d2);
    left: 0.5rem;
    opacity: 0;
    padding: 0.5em 0.75em;
    position: absolute;
    top: 0.5rem;
    transition: opacity 150ms linear;
  }

  .animationGrid:focus::after,
  .animationGrid:hover::after {
    opacity: 1;
  }

  .animationGrid img {
    display: block;
    height: 100%;
    object-fit: cover;
    width: 100%;
  }
</style>

<div class="animationGrid">
  {#each animationSequences as { id, image, url }}
    <a class="animationGrid-item" href={url} rel="noopener noreferrer" target="_blank" data-id={id}>
      <img src={image.url} alt={image.title} />
    </a>
  {/each}
</div>
