// src/components/FilmCard/index.tsx
import * as preact from '/web_modules/preact.js';
import { Link } from '/web_modules/preact-router.js';

import SkeletonImg from '../SkeletonImg/index.js';
import SkeletonText from '../SkeletonText/index.js';

interface FilmCardProps {
  id: string;
  image?: string;
  meta?: string;
  releaseYear: number;
  skeleton?: boolean;
  title: string;
  titleEN: string;
}

const FilmCard: preact.FunctionComponent<FilmCardProps> = ({
  id,
  image,
  meta,
  releaseYear,
  skeleton,
  title,
  titleEN,
}) =>
  !skeleton ? (
    <Link activeClassName="is-active" href={`/film/${id}`} className="filmCard">
      <div className="filmCard-img">
        <img alt={title} src={image} height="425" width="300" />
      </div>
      <h3 className="filmCard-title">
        {title}
        {titleEN !== title && [<br />, titleEN]}
      </h3>
      <div className="filmCard-year">{releaseYear}</div>
      {meta}
    </Link>
  ) : (
    <div className="filmCard">
      <div className="filmCard-img">
        <SkeletonImg />
      </div>
      <h3 className="filmCard-title">
        <SkeletonText>{title}</SkeletonText>
        <small>
          <SkeletonText>{meta}</SkeletonText>
        </small>
      </h3>
      <div className="filmCard-year">
        <SkeletonText>{releaseYear}</SkeletonText>
      </div>
    </div>
  );

export default FilmCard;

// src/components/FilmCard.svelte
<script>
  import { Link } from 'svelte-routing';
  import SkeletonImg from '../SkeletonImg/index.js';
  import SkeletonText from '../SkeletonText/index.js';

  export let id;
  export let image;
  export let meta = {};
  export let releaseYear;
  export let skeleton;
  export let title;
  export let titleEN;
</script>

<style>
  .filmCard {
    color: var(--fg);
    display: flex;
    flex-direction: column;
    text-decoration: none;
  }

  .filmCard-title {
    font-size: 1em;
    font-weight: 400;
    margin-block-end: 0;
    margin-block-start: 0;
  }

  .filmCard-title small {
    display: block;
    font-size: var(--d2);
  }

  .filmCard-img {
    border-radius: 0.25rem;
    display: block;
    margin-bottom: 0.5rem;
    max-width: 100%;
    height: calc(300px / var(--oneSheet));
    overflow: hidden;
    width: 300px;
  }

  .filmCard-img img {
    height: 100%;
    object-fit: cover;
    width: 100%;
  }
</style>

{#if !skeleton}
  <Link to={`/film/${id}`} class="filmCard">
    <div class="filmCard-img">
      <img alt={title} src={image} height="425" width="300" />
    </div>
    <h3 class="filmCard-title">
      {title}
      {#if titleEN !== title}
        <br />
        {titleEN}
      {/if}
    </h3>
    <div class="filmCard-year">{releaseYear}</div>
    {meta}
  </Link>
{:else}
  <div class="filmCard">
    <div class="filmCard-img">
      <SkeletonImg />
    </div>
    <h3 class="filmCard-title">
      <SkeletonText>{title}</SkeletonText>
      <small>
        <SkeletonText>{meta}</SkeletonText>
      </small>
    </h3>
    <div class="filmCard-year">
      <SkeletonText>{releaseYear}</SkeletonText>
    </div>
  </div>
{/if}
