// src/components/PersonLink/index.tsx
import * as preact from '/web_modules/preact.js';
import { Link } from '/web_modules/preact-router.js';
import { OneFilmQuery } from '../../types/graphql';

interface PersonLinkProps {
  person: OneFilmQuery['film']['directors'][0];
}

const PersonLink: preact.FunctionComponent<PersonLinkProps> = ({ person }) => (
  <Link className="personLink" href={`/person/${person.id}`}>
    <div className="personLink-avatar">
      <img src={person.image.url} alt={person.image.title} />
    </div>
    {person.alias ? person.alias : `${person.firstName} ${person.lastName}`}
  </Link>
);

export default PersonLink;

// src/components/PersonLink.vue
<script>
export default {
  props: {
    person: Object,
  },
};
</script>
<template>
  <router-link v-if="person" class="ani-imagelink" :to="`/person/${person.id}`">
    <div class="ani-imagelink-crop">
      <img class="ani-imagelink-img" :src="person.image.url" :alt="person.image.title" />
    </div>
    {{ person.alias ? person.alias : `${person.firstName} ${person.lastName}` }}
  </router-link>
</template>
