// src/components/StudioLink.svelte
<script>
  import { Link } from 'svelte-routing';

  // props
  export let studio = { image: {} };
</script>

<style>
  .studioLink {
    display: inline-block;
  }

  .studioLink-avatar {
    border-radius: 50%;
    display: inline-block;
    height: 2rem;
    margin-inline-end: 0.75em;
    overflow: hidden;
    vertical-align: middle;
    width: 2rem;
  }

  .studioLink-avatar img {
    height: 100%;
    object-fit: cover;
    width: 100%;
  }
</style>

<Link class="studioLink" to={`/studio/${studio.id}`}>
  <div class="studioLink-avatar">
    <img src={studio.image.url} alt={studio.image.title} />
  </div>
  {studio.name}
</Link>

// src/components/StudioLink.vue
<script>
export default {
  props: {
    studio: Object,
  },
};
</script>
<template>
  <router-link v-if="studio" class="ani-imagelink" :to="`/studio/${studio.id}`">
    <div class="ani-imagelink-crop">
      <img class="ani-imagelink-img" :src="studio.image.url" :alt="studio.image.title" />
    </div>
    {{ studio.name }}
  </router-link>
</template>
