// src/components/App/index.tsx
import * as preact from '/web_modules/preact.js';
import Router from '/web_modules/preact-router.js';
import HomePage from '../../pages/index.js';
import FilmPage from '../../pages/film.js';
import PersonPage from '../../pages/person.js';
import StudioPage from '../../pages/studio.js';

const App: preact.FunctionComponent = () => (
  <Router>
    <HomePage path="/" />
    <FilmPage path="/film/:id" />
    <PersonPage path="/person/:id" />
    <StudioPage path="/studio/:id" />
  </Router>
);

export default App;

// src/App.svelte
<script>
  import { Router, Route } from 'svelte-routing';
  import Home from '../routes/Home.svelte';
  import Film from '../routes/Film.svelte';
  import Person from '../routes/Person.svelte';
  import Studio from '../routes/Studio.svelte';
</script>

<Router>
  <Route path="/" component={Home} />
  <Route path="/film/:id" component={Film} />
  <Route path="/person/:id" component={Person} />
  <Route path="/studio/:id" component={Studio} />
</Router>
